### ISSUE TITLE
Simple fix for running samples OK on RX Vega..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#2]
Hi,
as mentioned in:
https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/issues/21
finally got samples to render correctly on RX Vega with AMD preview driver (30.0.21001.1004 22.10.01.01-220412a):
still a fix is needed: for samples working on RX Vega need to comment:
//#include <hiprt/hiprt_device.h>
in TestKernel.h all samples

**Comment by takahiroharada** [comment]
Linking to the other issue you reported https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/issues/21

**Comment by PixelClear** [comment]
we have made a fix for the header issue please give the try latest repo and do let us know if it resolves the issue for you.

**Comment by PixelClear** [comment]
For now, we will be closing this issue as we have made some updates from our side. Please do give it a try and reopen it if you are still seeing the issue.

**Comment by PixelClear** [comment]
Please give try to latest driver : https://www.amd.com/en/support/graphics/radeon-rx-vega-series/radeon-rx-vega-series/radeon-rx-vega-64
The rendering issue is fixed in this. 

For need to comment //#include <hiprt/hiprt_device.h> issue 
Please download the latest SDK we have fixed that issue there.
