### ISSUE TITLE
[Question]: Saving BVH

### ISSUE THREAD

**Issue by ib00** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#33]
There's an example of how HIPRT uses a user provided BVH.

What about creating a BVH of some scene with HIPRT and then saving it out to a file for 
later import. Is there an example for that?

**Comment by meistdan** [comment]
There is no tutorial for that, but you can save `hiprtGeometry` (BLAS) to a file. Here is an example how to do that: https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/blob/main/test/main.cpp#L822-L907

We haven't implemented this for the `hiprtScene`. There is an issue with the (device) pointers that need to be remapped correctly when loading the data back. The problem is that the scene and geometries are treated separately.
